# Generated by Django 6.0 on 2025-12-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='category_images',
            new_name='Category_images',
        ),
    ]
