# Generated by Django 6.0 on 2025-12-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_rename_category_images_categorydb_category_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Author_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Additional_info', models.TextField(blank=True, null=True)),
                ('Overview', models.TextField(blank=True, null=True)),
                ('product_img1', models.ImageField(blank=True, null=True, upload_to='Product Images')),
                ('Product_img2', models.ImageField(blank=True, null=True, upload_to='Product Images')),
                ('Product_img3', models.ImageField(blank=True, null=True, upload_to='Product Images')),
            ],
        ),
    ]
