# Generated by Django 6.0 on 2025-12-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='product_img1',
            new_name='Product_img1',
        ),
    ]
