# Generated by Django 6.0 on 2026-01-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_rename_product_img1_productdb_product_img1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='Product_img1',
        ),
        migrations.RemoveField(
            model_name='productdb',
            name='Product_img2',
        ),
        migrations.RemoveField(
            model_name='productdb',
            name='Product_img3',
        ),
    ]
