# Generated by Django 6.0 on 2026-01-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_remove_productdb_product_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Product_img',
            field=models.ImageField(blank=True, null=True, upload_to='Product Images'),
        ),
    ]
