# Generated by Django 6.0 on 2026-01-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_productdb_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='Additional_info',
        ),
    ]
