# Generated by Django 6.0 on 2026-03-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Place', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
                ('Mobile', models.BigIntegerField(blank=True, null=True)),
                ('Total_price', models.CharField(blank=True, max_length=100, null=True)),
                ('Razorpay_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('Razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('Razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('Payment_status', models.CharField(blank=True, default='Pending', max_length=30, null=True)),
            ],
        ),
    ]
